name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  proto:
    name: Lint and breaking change check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        with:
          lint: true
          format: true
          breaking: true
          breaking_against: https://github.com/${{ github.repository }}.git#branch=${{ github.base_ref }}
          push: false
