name: Publish

on:
  push:
    branches: [main, develop]

jobs:
  publish:
    name: Push to Buf Schema Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: false
          format: false
          breaking: true
          breaking_against: buf.build/xpendsense/spendsense
          push: true
